"use client";

import { useState } from "react";
import useSWR from "swr";
import { format } from "date-fns";
import {
    FileText,
    Download,
    ShieldCheck,
    Eye,
    Loader2,
    CheckCircle,
    AlertTriangle
} from "lucide-react";

import { Button } from "@/components/ui/button";
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from "@/components/ui/card";
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from "@/components/ui/table";
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from "@/components/ui/dialog";
import { TamperProofBadge } from "@/components/shared/TamperProofBadge";
import { StatusBadge } from "@/components/shared/StatusBadge";
import { DateRangePicker } from "@/components/shared/DateRangePicker";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";

const fetcher = (url: string) => fetch(url).then((res) => res.json());

export default function ReportsPage() {
    const [page, setPage] = useState(1);
    const [evidenceMode, setEvidenceMode] = useState(false);
    const { data, error, isLoading } = useSWR(
        `/api/reports?page=${page}&limit=10`,
        fetcher
    );

    const [verifyingId, setVerifyingId] = useState<string | null>(null);
    const [verificationResult, setVerificationResult] = useState<any>(null);

    const handleVerify = async (reportId: string) => {
        setVerifyingId(reportId);
        setVerificationResult(null);
        try {
            const res = await fetch(`/api/reports/${reportId}/verify`);
            const result = await res.json();
            setVerificationResult(result);
        } catch (err) {
            console.error("Verification failed", err);
            setVerificationResult({ verified: false, message: "Verification request failed" });
        } finally {
            setVerifyingId(null);
        }
    };

    return (
        <div className={`space-y-6 transition-all duration-500 ${evidenceMode ? "max-w-5xl mx-auto pt-10" : ""}`}>
            <div className="flex items-center justify-between">
                <div className="flex flex-col gap-2">
                    <h1 className="text-3xl font-bold tracking-tight text-slate-900 dark:text-slate-100">
                        {evidenceMode ? "Audit Evidence Ledger" : "Compliance Reports"}
                    </h1>
                    <p className="text-muted-foreground">
                        {evidenceMode
                            ? "immutable. verified. signature-enforced."
                            : "Manage and verify tamper-evident audit reports."}
                    </p>
                </div>
                <div className="flex items-center space-x-2 bg-slate-100 dark:bg-slate-800 p-2 rounded-lg border">
                    <Switch id="evidence-mode" checked={evidenceMode} onCheckedChange={setEvidenceMode} />
                    <Label htmlFor="evidence-mode" className="text-sm font-medium cursor-pointer">Evidence Mode</Label>
                </div>
            </div>

            {!evidenceMode && (
                <div className="flex items-center justify-between">
                    <DateRangePicker onChange={() => { }} />
                    <Button>
                        <FileText className="mr-2 h-4 w-4" />
                        Generate New Report
                    </Button>
                </div>
            )}

            <Card className={evidenceMode ? "border-2 border-slate-900 shadow-2xl scale-[1.01] transition-all" : ""}>
                <CardHeader>
                    <CardTitle>Generated Reports</CardTitle>
                    <CardDescription>
                        A secure ledger of all compliance documentation generated by the system.
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    {isLoading ? (
                        <div className="flex justify-center p-8">
                            <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
                        </div>
                    ) : error ? (
                        <div className="text-center p-8 text-rose-500">
                            Failed to load reports. Please try again.
                        </div>
                    ) : !data?.data?.length ? (
                        <div className="text-center p-8 text-muted-foreground">
                            No reports found. Generate one to get started.
                        </div>
                    ) : (
                        <Table>
                            <TableHeader>
                                <TableRow>
                                    <TableHead>Report ID</TableHead>
                                    <TableHead>Period</TableHead>
                                    <TableHead>Generated At</TableHead>
                                    <TableHead>Status</TableHead>
                                    <TableHead>Integrity Hash</TableHead>
                                    <TableHead className="text-right">Actions</TableHead>
                                </TableRow>
                            </TableHeader>
                            <TableBody>
                                {data.data.map((report: any) => (
                                    <TableRow key={report.id}>
                                        <TableCell className="font-mono text-xs text-muted-foreground">
                                            {report.id.slice(0, 8)}...
                                        </TableCell>
                                        <TableCell>
                                            {format(new Date(report.periodStart), "MMM d")} - {format(new Date(report.periodEnd), "MMM d, yyyy")}
                                        </TableCell>
                                        <TableCell>
                                            {format(new Date(report.createdAt), "PP p")}
                                        </TableCell>
                                        <TableCell>
                                            <StatusBadge status={report.status as any} />
                                        </TableCell>
                                        <TableCell>
                                            <TamperProofBadge hash={report.reportHash} verified={true} />
                                        </TableCell>
                                        <TableCell className="text-right">
                                            <div className="flex justify-end gap-2">
                                                <Dialog>
                                                    <DialogTrigger asChild>
                                                        <Button variant="ghost" size="sm" onClick={() => handleVerify(report.id)}>
                                                            <ShieldCheck className="h-4 w-4 mr-1" />
                                                            Verify
                                                        </Button>
                                                    </DialogTrigger>
                                                    <DialogContent>
                                                        <DialogHeader>
                                                            <DialogTitle>Report Integrity Verification</DialogTitle>
                                                            <DialogDescription>
                                                                Verifying the cryptographic signature of this document against the immutable ledger.
                                                            </DialogDescription>
                                                        </DialogHeader>
                                                        <div className="py-4 space-y-4">
                                                            {verifyingId === report.id ? (
                                                                <div className="flex items-center gap-2 text-muted-foreground">
                                                                    <Loader2 className="h-4 w-4 animate-spin" />
                                                                    Verifying hash...
                                                                </div>
                                                            ) : verificationResult ? (
                                                                <div className={`p-4 rounded-lg border ${verificationResult.verified ? 'bg-emerald-50/50 border-emerald-200 text-emerald-800' : 'bg-rose-50/50 border-rose-200 text-rose-800'}`}>
                                                                    <div className="flex items-center gap-2 font-semibold mb-2">
                                                                        {verificationResult.verified ? (
                                                                            <CheckCircle className="h-5 w-5" />
                                                                        ) : (
                                                                            <AlertTriangle className="h-5 w-5" />
                                                                        )}
                                                                        {verificationResult.verified ? "Integrity Verified" : "Verification Failed"}
                                                                    </div>
                                                                    <p className="text-sm">{verificationResult.message}</p>
                                                                    <div className="mt-4 text-xs font-mono bg-white/50 p-2 rounded">
                                                                        <div className="flex justify-between">
                                                                            <span>Stored Hash:</span>
                                                                            <span>{verificationResult.originalHash?.slice(0, 20)}...</span>
                                                                        </div>
                                                                        <div className="flex justify-between font-bold">
                                                                            <span>Computed Hash:</span>
                                                                            <span>{verificationResult.currentHash?.slice(0, 20)}...</span>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            ) : null}
                                                        </div>
                                                    </DialogContent>
                                                </Dialog>

                                                <Button variant="outline" size="sm" asChild>
                                                    <a href={report.pdfUrl} target="_blank" rel="noopener noreferrer">
                                                        <Download className="h-4 w-4 mr-1" />
                                                        PDF
                                                    </a>
                                                </Button>
                                            </div>
                                        </TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    )}
                </CardContent>
            </Card>
        </div>
    );
}
