import puppeteer from 'puppeteer';
import { generateReportHash } from './hashUtils';

interface ReportData {
    organizationName: string;
    periodStart: Date;
    periodEnd: Date;
    totalEvents: number;
    totalViolations: number;
    compliantSessions: number;
    events: Array<{
        timestamp: Date;
        tool: string;
        user: string;
        action: string;
        riskScore: number;
    }>;
    generatedBy: string;
    generatedAt: Date;
}

/**
 * Generate HTML template for compliance report
 */
function generateReportHTML(data: ReportData): string {
    const eventRows = data.events.map(event => `
        <tr>
            <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">${event.timestamp.toLocaleString()}</td>
            <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">${event.tool}</td>
            <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">${event.user}</td>
            <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">
                <span style="padding: 2px 8px; border-radius: 4px; font-size: 12px; background-color: ${event.action === 'allowed' ? '#d1fae5' : '#fecaca'}; color: ${event.action === 'allowed' ? '#065f46' : '#991b1b'};">
                    ${event.action}
                </span>
            </td>
            <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; text-align: center;">${event.riskScore}</td>
        </tr>
    `).join('');

    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AuditShield Compliance Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 40px; color: #1f2937; }
        .header { border-bottom: 3px solid #4f46e5; padding-bottom: 20px; margin-bottom: 30px; }
        .header h1 { font-size: 28px; color: #1f2937; margin-bottom: 8px; }
        .header p { color: #6b7280; font-size: 14px; }
        .meta { display: flex; justify-content: space-between; margin-bottom: 30px; padding: 20px; background: #f9fafb; border-radius: 8px; }
        .meta-item strong { display: block; color: #6b7280; font-size: 12px; margin-bottom: 4px; font-weight: 500; }
        .meta-item span { color: #1f2937; font-size: 16px; font-weight: 600; }
        .stats { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin-bottom: 30px; }
        .stat-card { padding: 20px; border: 1px solid #e5e7eb; border-radius: 8px; }
        .stat-card .label { font-size: 12px; color: #6b7280; margin-bottom: 8px; }
        .stat-card .value { font-size: 32px; font-weight: 700; color: #1f2937; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        th { background: #f3f4f6; padding: 12px 8px; text-align: left; font-size: 12px; font-weight: 600; color: #6b7280; text-transform: uppercase; border-bottom: 2px solid #e5e7eb; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #9ca3af; }
        .tamper-notice { background: #fef3c7; border-left: 4px solid #f59e0b; padding: 16px; margin-top: 20px; font-size: 12px; color: #92400e; }
    </style>
</head>
<body>
    <div class="header">
        <h1>🛡️ AuditShield Compliance Report</h1>
        <p>${data.organizationName}</p>
    </div>

    <div class="meta">
        <div class="meta-item">
            <strong>Report Period</strong>
            <span>${data.periodStart.toLocaleDateString()} - ${data.periodEnd.toLocaleDateString()}</span>
        </div>
        <div class="meta-item">
            <strong>Generated By</strong>
            <span>${data.generatedBy}</span>
        </div>
        <div class="meta-item">
            <strong>Generated At</strong>
            <span>${data.generatedAt.toLocaleString()}</span>
        </div>
    </div>

    <div class="stats">
        <div class="stat-card">
            <div class="label">Total AI Events</div>
            <div class="value">${data.totalEvents.toLocaleString()}</div>
        </div>
        <div class="stat-card">
            <div class="label">Policy Violations</div>
            <div class="value" style="color: #dc2626;">${data.totalViolations.toLocaleString()}</div>
        </div>
        <div class="stat-card">
            <div class="label">Compliant Sessions</div>
            <div class="value" style="color: #059669;">${data.compliantSessions.toLocaleString()}</div>
        </div>
    </div>

    <h2 style="font-size: 18px; margin-bottom: 16px; color: #1f2937;">Audit Events</h2>
    <table>
        <thead>
            <tr>
                <th>Timestamp</th>
                <th>AI Tool</th>
                <th>User</th>
                <th>Action</th>
                <th style="text-align: center;">Risk Score</th>
            </tr>
        </thead>
        <tbody>
            ${eventRows}
        </tbody>
    </table>

    <div class="tamper-notice">
        <strong>⚠️ Tamper-Evident Report</strong><br>
        This report is cryptographically signed using SHA-256 hashing to ensure its integrity. Any modification to the content will invalidate the signature and be detectable during verification.
    </div>

    <div class="footer">
        <p><strong>AuditShield</strong> - Compliance-grade AI Usage Auditing</p>
        <p>This report is generated for compliance and audit purposes. Unauthorized distribution is prohibited.</p>
    </div>
</body>
</html>
    `;
}

/**
 * Generate PDF report from data
 * Returns PDF buffer and SHA-256 hash for tamper-evidence
 */
export async function generatePDFReport(data: ReportData): Promise<{
    pdfBuffer: Buffer;
    hash: string;
}> {
    const html = generateReportHTML(data);

    // Launch headless browser
    const browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
    });

    try {
        const page = await browser.newPage();
        await page.setContent(html, { waitUntil: 'networkidle0' });

        // Generate PDF
        const pdfBuffer = await page.pdf({
            format: 'A4',
            printBackground: true,
            margin: {
                top: '20mm',
                right: '15mm',
                bottom: '20mm',
                left: '15mm',
            },
        }) as Buffer;

        // Generate hash
        const hash = generateReportHash(pdfBuffer);

        return { pdfBuffer, hash };
    } finally {
        await browser.close();
    }
}
