import { NextResponse } from 'next/server';
import puppeteer from 'puppeteer';
import { db } from '@/lib/db';
import { auditEvents, organizations } from '@/db/schema';
import { desc } from 'drizzle-orm';

// NOTE: In a real Vercel deployment, you would use 'puppeteer-core' and '@sparticuz/chromium'
// because standard Puppeteer is too large for Serverless Function limits.
// For this MVP/Local demo, standard Puppeteer is fine.

export async function POST(req: Request) {
    try {
        // 1. Fetch Data
        const events = await db.select().from(auditEvents).orderBy(desc(auditEvents.createdAt)).limit(50);
        const orgs = await db.select().from(organizations).limit(1);
        const orgName = orgs[0]?.name || 'Organization';

        // 2. Build HTML Template
        const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { font-family: sans-serif; padding: 40px; color: #333; }
          h1 { color: #0f172a; border-bottom: 2px solid #0f172a; padding-bottom: 10px; }
          .header { display: flex; justify-content: space-between; margin-bottom: 40px; }
          .meta { font-size: 0.9rem; color: #64748b; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th { text-align: left; background: #f1f5f9; padding: 10px; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; }
          td { border-bottom: 1px solid #e2e8f0; padding: 10px; font-size: 0.9rem; }
          .footer { margin-top: 50px; font-size: 0.8rem; text-align: center; color: #94a3b8; }
          .hash { font-family: monospace; font-size: 0.8rem; background: #f8fafc; padding: 2px 4px; border-radius: 4px; }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <h1>Compliance Audit Report</h1>
            <div class="meta">Prepared for: <strong>${orgName}</strong></div>
          </div>
          <div style="text-align: right;">
            <div class="meta">Date: ${new Date().toLocaleDateString()}</div>
            <div class="meta">Report ID: ${crypto.randomUUID().slice(0, 8)}</div>
          </div>
        </div>

        <table>
          <thead>
            <tr>
              <th>Time</th>
              <th>Domain</th>
              <th>Event Type</th>
              <th>Hash</th>
            </tr>
          </thead>
          <tbody>
            ${events.map(event => `
              <tr>
                <td>${new Date(event.createdAt!).toLocaleString()}</td>
                <td><strong>${event.domain}</strong></td>
                <td>${event.eventType}</td>
                <td class="hash">${event.id.slice(0, 8)}...</td>
              </tr>
            `).join('')}
          </tbody>
        </table>

        <div class="footer">
          Generated by AuditShield • Tamper-Evident AI Compliance
        </div>
      </body>
      </html>
    `;

        // 3. Generate PDF with Puppeteer
        const browser = await puppeteer.launch();
        const page = await browser.newPage();
        await page.setContent(htmlContent);
        const pdfBuffer = await page.pdf({ format: 'A4', printBackground: true });
        await browser.close();

        // 4. Return PDF
        return new NextResponse(pdfBuffer as unknown as BodyInit, {
            headers: {
                'Content-Type': 'application/pdf',
                'Content-Disposition': `attachment; filename="audit_report_${Date.now()}.pdf"`,
            },
        });

    } catch (error) {
        console.error('PDF Generation Error:', error);
        return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 });
    }
}
